# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do predictions for ScreeningModel1
#' @param t double vector of times to evaluate
#' @param tj double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @return data-frame with elements time, X, Y, Z (for state probabilities) and I (for incidence)
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_1_predictions(t=x, tj=vector("double"), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_1_predictions(t=x, tj=c(10,15, 20, 25), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_1_predictions <- function(time, tj, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta = 0.05) {
    .Call('_screening_screening_model_1_predictions', PACKAGE = 'screening', time, tj, shape1, scale1, shape2, scale2, beta)
}

#' Do likelihood calculations for ScreeningModel1
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param tj double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @return list with element t for the times t and element p for a numeric matrix of the probabilities, including column names X, Y and Z.
#' @export
screening_model_1_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta = 0.05) {
    .Call('_screening_screening_model_1_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta)
}

