# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Do predictions for ScreeningModel1
#' @name ScreeningModel1
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_1_predictions(t=x, tj=vector("double"), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_1_predictions(t=x, tj=c(10,15, 20, 25), shape1=1.5, shape2=1.5, scale1=20, scale2=10, beta=0.4) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_1_predictions <- function(t, ti, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta = 0.05, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_1_predictions', PACKAGE = 'screening', t, ti, shape1, scale1, shape2, scale2, beta, simple, tol)
}

#' Do likelihood calculations for ScreeningModel1
#' @name ScreeningModel1
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta false negative fraction for screening
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_1_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta = 0.05, tol = 1e-6) {
    .Call('_screening_screening_model_1_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta, tol)
}

#' Do predictions for ScreeningModel2
#' @name ScreeningModel2
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param yi double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_2_predictions(t=x, ti=vector("double"), yi=vector("double"), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_2_predictions(t=x, ti=c(10,15, 20, 25), yi=c(3,3,3), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_2_predictions <- function(t, ti, yi, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta0 = -3.0, beta1 = 1.0, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_2_predictions', PACKAGE = 'screening', t, ti, yi, shape1, scale1, shape2, scale2, beta0, beta1, simple, tol)
}

#' Do likelihood calculations for ScreeningModel2
#' @name ScreeningModel2
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_2_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta0 = -3.0, beta1 = 1.0, tol = 1e-6) {
    .Call('_screening_screening_model_2_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta0, beta1, tol)
}

#' Do predictions for ScreeningModel3
#' @name ScreeningModel3
#' @param t double vector of times to evaluate
#' @param ti double vector of screening times
#' @param yi double vector of screening times
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param simple whether to calculate Z using a simple method (complement) or integration (defaults to true)
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return data-frame with elements t, X, Y, Z (for state probabilities) and I (for incidence)
#' @importFrom Rcpp sourceCpp
#' @examples
#' par(mfrow=1:2)
#' x=seq(0,30,length=301)
#' screening_model_3_predictions(t=x, ti=vector("double"), yi=vector("double"), bxi=vector("integer"), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="No screening"))
#' screening_model_3_predictions(t=x, ti=c(10,15, 20, 25), yi=c(3,3,3), bxi=c(FALSE,FALSE,TRUE), shape1=1.5, shape2=1.5, scale1=20, scale2=10) |>
#'     with(matplot(time,cbind(X,Y,Z),type="l", lty=1, main="Screening"))
#' @export
screening_model_3_predictions <- function(t, ti, yi, bxi, shape1 = 1, scale1 = 1, shape2 = 1, scale2 = 1, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, simple = TRUE, tol = 1e-6) {
    .Call('_screening_screening_model_3_predictions', PACKAGE = 'screening', t, ti, yi, bxi, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, simple, tol)
}

#' Do likelihood calculations for ScreeningModel3
#' @name ScreeningModel3
#' @param inputs list of list with elements of t for the evaluation time, tj for the screening times and type for the type of likelihood (1=No cancer detected, 2=Screen-detected cancer, 3=Interval cancer)
#' @param scale1 Weibull scale for onset
#' @param shape Weibull shape for onset
#' @param shape2 Weibull shape for clinical diagnosis
#' @param scale2 Weibull scale for clinical diagnosis
#' @param beta0 intercept for logistic model for false negative fraction
#' @param beta1 slope of log(yi) for logistic model for false negative fraction
#' @param PrFalseNegBx probability of a false negative biopsy | cancer, biopsy undertaken
#' @param tol double for the numeric tolerance of the integration (default=1e-6)
#' @return vector of likelihoods
#' @export
screening_model_3_likes <- function(inputs, shape1 = 1.0, scale1 = 1.0, shape2 = 1.0, scale2 = 1.0, beta0 = -3.0, beta1 = 1.0, PrFalseNegBx = 0.05, tol = 1e-6) {
    .Call('_screening_screening_model_3_likes', PACKAGE = 'screening', inputs, shape1, scale1, shape2, scale2, beta0, beta1, PrFalseNegBx, tol)
}

